In [1]:
# synthetic regression datasets
from sklearn.datasets import make_regression
X,Y = make_regression(n_samples=100,n_features=3,n_informative=2,random_state=1)

c:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
X.shape # no of inputs,no of features

(100, 3)

In [3]:
Y.shape # no of output 

(100,)

In [4]:
Y

array([-1.04439256e+02,  6.31378200e+01,  3.57606596e+01,  1.86878803e+02,
        3.95268134e+01, -1.12321735e+01,  7.64976566e+01, -1.45698167e+02,
        5.05541723e+01, -5.36390735e+01, -5.69318174e+01,  4.60362622e+01,
       -4.46307507e+01,  9.97431896e+01, -1.63207115e+01, -1.07453234e+01,
       -3.79996891e+01,  9.65786941e+01, -1.34801081e+01,  7.99212630e+00,
       -7.77643084e+01,  3.28339052e+01,  2.76791237e+01,  2.68550680e+01,
        2.25054343e+00,  3.81428311e+01,  1.55963072e+00,  4.51424650e-02,
       -1.07170071e+02, -7.96555334e+01,  2.16345268e+01, -6.25743778e+00,
       -3.57413352e+01, -2.11289592e+01, -7.70388970e+01, -1.61257183e+02,
       -1.55308856e+02,  7.40131107e+01, -3.65834879e+01,  1.52382617e+01,
        5.78063296e+01,  5.23516542e+01,  1.48784231e+02,  4.96428187e+01,
        2.91520981e+00, -2.10283412e+01,  5.44848335e+01, -9.86752139e+00,
        6.54120911e+01,  1.03020310e+02,  5.07248558e+01,  4.84234725e+00,
        4.73624085e+01,  

In [5]:
import pandas as pd
df = pd.DataFrame(X,columns=['X1','X2','X3'])

In [6]:
df['Y'] = Y

In [7]:
df

X1        X2        X3           Y
0  -1.119115 -0.890556  1.956079 -104.439256
1   0.846161  0.315159 -0.859516   63.137820
2   0.582815  0.042214 -1.100619   35.760660
3   2.528326  0.901487 -0.248635  186.878803
4   1.252868 -0.754398  0.512930   39.526813
..       ...       ...       ...         ...
95 -0.955425  0.784771  0.585910  -20.886024
96  0.240737  0.562761  0.280665   38.869379
97 -0.203394 -0.700399  0.242669  -42.779871
98  0.043597 -0.343854 -0.620001  -12.659546
99  0.441364  2.186980 -0.100155  122.312326

[100 rows x 4 columns]

In [8]:
# synthetic regression datasets
from sklearn.datasets import make_regression
X,Y = make_regression(n_samples=100,n_features=3,n_informative=2,random_state=1,n_targets=2)

In [9]:
Y.shape

(100, 2)

In [10]:
# inbuilt datasets
# TOY datasets
# realworld datasets
# Kaggle
# UCI ML datasets

In [11]:
# Univariate Regression
df = pd.read_csv("Salary_Data.csv")
df.shape

(30, 2)

In [12]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [13]:
df.shape[0]

30

In [14]:
import numpy as np
np.random.seed(1)
np.random.choice(df.shape[0],5)

array([ 5, 11, 12,  8,  9])

In [15]:
import random
random.seed(1)
ind = random.sample(list(range(df.shape[0])),5)
ind

[4, 18, 27, 25, 24]

In [16]:
df.loc[ind] # taking data from random samples

YearsExperience    Salary
4               2.2   39891.0
18              5.9   81363.0
27              9.6  112635.0
25              9.0  105582.0
24              8.7  109431.0

In [21]:
df.loc[ind]['YearsExperience'].values.reshape(-1,1)

array([[2.2],
       [5.9],
       [9.6],
       [9. ],
       [8.7]])

In [22]:
# KNN (K -Nearest Neidhbors)
# where k is the no of neighbors used for making predictions

from sklearn.neighbors import KNeighborsRegressor
# f : 1NN with distance metric manhattan
knn = KNeighborsRegressor(n_neighbors=1,metric='manhattan')
knn.fit(df.loc[ind]['YearsExperience'].values.reshape(-1,1),df.loc[ind]['Salary'])

KNeighborsRegressor(metric='manhattan', n_neighbors=1)

In [23]:
df.loc[ind]

YearsExperience    Salary
4               2.2   39891.0
18              5.9   81363.0
27              9.6  112635.0
25              9.0  105582.0
24              8.7  109431.0

In [24]:
knn.predict([[2],[5]])

array([39891., 81363.])

In [25]:
# f : 2NN with distance metric manhattan - uniform
knn = KNeighborsRegressor(n_neighbors=2,metric='manhattan',weights='uniform') # default "uniform"
knn.fit(df.loc[ind]['YearsExperience'].values.reshape(-1,1),df.loc[ind]['Salary'].values)

KNeighborsRegressor(metric='manhattan', n_neighbors=2)

In [27]:
knn.predict([[5]])

array([60627.])

In [47]:
# f : 2NN with distance metric manhattan - distance
knn = KNeighborsRegressor(n_neighbors=2,metric='manhattan',weights='distance') # default "uniform"
knn.fit(df.loc[ind]['YearsExperience'].values.reshape(-1,1),df.loc[ind]['Salary'])

KNeighborsRegressor(metric='manhattan', n_neighbors=2, weights='distance')

In [48]:
knn.predict([[5]])

AttributeError: 'list' object has no attribute 'shape'

In [52]:
knn.predict(np.array(2.1).reshape(1,1))

array([40954.38461538])

In [53]:
np.array([2.1])

array([2.1])

In [ ]:
# split the dataset into 2 parts
# 1. train --> to get predictions
# 2. test --> wil be used to evaluate how good your predictions are

In [98]:
X = df['YearsExperience'].values.reshape(30,1) # input
Y = df['Salary'].values # output

In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =  train_test_split(X,Y,test_size=0.3,random_state=1)

In [63]:
x_train.shape

(21, 1)

In [64]:
x_test.shape

(9, 1)

In [65]:
y_train.shape

(21,)

In [66]:
y_test.shape

(9,)

In [67]:
knn = KNeighborsRegressor(n_neighbors=1,metric="euclidean")
knn.fit(x_train,y_train)

KNeighborsRegressor(metric='euclidean', n_neighbors=1)

In [68]:
y_pred =  knn.predict(x_test)

In [69]:
y_test

array([ 83088.,  98273.,  63218.,  93940.,  61111.,  91738., 116969.,
        43525., 109431.])

In [70]:
y_test-knn.predict(x_test)

array([17059., -3029.,  6261., 12577.,  4030., 10375.,  4334.,  3634.,
        3849.])

In [71]:
np.abs(y_test-y_pred).sum() # sum of absolute error SAE

65148.0

In [73]:
((y_test-y_pred)**2).sum() # sum of squared error SSE

668251210.0

In [75]:
np.abs(y_test-y_pred).mean() # mean of absolute error

7238.666666666667

In [77]:
((y_test-y_pred)**2).mean() # mean of squared error

74250134.44444445

In [ ]:
# lower the better --> SAE,SSE,MAE,MSE [Negative evaluation metric]

In [78]:
# Higher the better  --> NSAE, NSSE, NMAE, NMSE  [Positive evaluation metric]

In [79]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_test)

74250134.44444445

In [80]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_pred,y_test)

7238.666666666667

In [82]:
from sklearn.metrics import mean_squared_error
SSE = mean_squared_error(y_pred,y_test)*y_pred.shape[0]
SSE

668251210.0

In [84]:
from sklearn.metrics import mean_absolute_error
SAE = mean_absolute_error(y_pred,y_test)*y_pred.shape[0]
SAE

65148.0

In [89]:
for k in range(1,11):
    for avg_type in ['uniform','distance']:
        knn = KNeighborsRegressor(n_neighbors=k,metric='manhattan',weights=avg_type)
        knn.fit(x_train,y_train)
        y_pred = knn.predict(x_test)
        print(mean_absolute_error(y_pred,y_test))

7238.666666666667
7238.666666666665
7457.722222222223
6555.141993873574
6265.481481481482
5708.028392829408
5159.055555555556
5334.409917193207
6428.199999999998
5459.583296455265
7730.833333333333
5662.938585201406
8478.04761904762
6033.2865160828505
9606.763888888889
6415.507545116786
11418.246913580246
7092.302856339625
13084.8
7774.099197837121


In [91]:
import sklearn
sorted(sklearn.neighbors.VALID_METRICS['brute'])

['braycurtis',
 'canberra',
 'chebyshev',
 'cityblock',
 'correlation',
 'cosine',
 'cosine',
 'dice',
 'euclidean',
 'hamming',
 'haversine',
 'jaccard',
 'kulsinski',
 'l1',
 'l2',
 'mahalanobis',
 'manhattan',
 'matching',
 'minkowski',
 'nan_euclidean',
 'precomputed',
 'rogerstanimoto',
 'russellrao',
 'seuclidean',
 'sokalmichener',
 'sokalsneath',
 'sqeuclidean',
 'wminkowski',
 'yule']

In [ ]:
# K fold cross validation

In [94]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 5)

In [95]:
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [99]:
for i in kf.split(X):
    print(i)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29]), array([0, 1, 2, 3, 4, 5]))
(array([ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29]), array([ 6,  7,  8,  9, 10, 11]))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29]), array([12, 13, 14, 15, 16, 17]))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 24, 25, 26, 27, 28, 29]), array([18, 19, 20, 21, 22, 23]))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23]), array([24, 25, 26, 27, 28, 29]))


In [101]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [102]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import KFold, cross_val_score

knn = KNeighborsRegressor(n_neighbors=2, metric="manhattan", weights="uniform")
kf = KFold(n_splits=5)

cross_val_score(knn,X,Y,cv=kf,scoring="neg_mean_absolute_error")

array([-13408.        ,  -4912.91666667,  -5567.58333333,  -9648.16666667,
        -7914.66666667])

In [103]:
cross_val_score(knn,X,Y,cv=kf,scoring="neg_mean_absolute_error").mean()

-8290.266666666666

In [104]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
from sklearn.model_selection import KFold,GridSearchCV
kf = KFold(n_splits=5)

combinations = {"n_neighbors" : range(1,11),
                "weights" : ['uniform','distance'],
                "metric"  : ["manhattan","euclidean"]                  
}

gcv = GridSearchCV(knn, param_grid=combinations, cv=kf, scoring="neg_mean_absolute_error" )
gcv.fit(X,Y)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=KNeighborsRegressor(),
             param_grid={'metric': ['manhattan', 'euclidean'],
                         'n_neighbors': range(1, 11),
                         'weights': ['uniform', 'distance']},
             scoring='neg_mean_absolute_error')

In [105]:
gcv.best_params_

{'metric': 'manhattan', 'n_neighbors': 1, 'weights': 'uniform'}

In [106]:
gcv.best_score_

-7805.866666666667

In [107]:
gcv.predict([[5]])

array([67938.])

In [110]:
gcv.best_estimator_

KNeighborsRegressor(metric='manhattan', n_neighbors=1)

In [109]:
gcv.best_estimator_.predict([[5]])

array([67938.])

In [111]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
from sklearn.model_selection import KFold,RandomizedSearchCV
kf = KFold(n_splits=5)

combinations = {"n_neighbors" : range(1,11),
                "weights" : ['uniform','distance'],
                "metric"  : ["manhattan","euclidean"]                  
}

rcv = RandomizedSearchCV(knn, param_distributions=combinations, cv=kf, scoring="neg_mean_absolute_error" )
rcv.fit(X,Y)

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=KNeighborsRegressor(),
                   param_distributions={'metric': ['manhattan', 'euclidean'],
                                        'n_neighbors': range(1, 11),
                                        'weights': ['uniform', 'distance']},
                   scoring='neg_mean_absolute_error')

In [112]:
rcv.best_params_

{'weights': 'uniform', 'n_neighbors': 1, 'metric': 'euclidean'}

In [114]:
rcv.best_estimator_

KNeighborsRegressor(metric='euclidean', n_neighbors=1)

In [116]:
rcv.best_score_

-7805.866666666667

In [117]:
from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing()
X = dataset.data
Y = dataset.target

In [120]:
X.shape

(20640, 8)

In [121]:
dataset.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [122]:
dataset.target_names

['MedHouseVal']

In [124]:
df = pd.DataFrame(X,columns=dataset.feature_names)
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [127]:
df.describe() # requires the feature scaling

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

In [ ]:
# example fornormalization and standardization

In [132]:
data = X[:5,:2]

from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit(data)

MinMaxScaler()

In [134]:
mm.transform(data)

array([[1.        , 0.64516129],
       [0.99468631, 0.        ],
       [0.76159857, 1.        ],
       [0.4011833 , 1.        ],
       [0.        , 1.        ]])

In [135]:
mm.fit_transform(data)

array([[1.        , 0.64516129],
       [0.99468631, 0.        ],
       [0.76159857, 1.        ],
       [0.4011833 , 1.        ],
       [0.        , 1.        ]])

In [136]:
data = X[:5,:2]

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit_transform(data)

array([[ 0.96018595, -0.21529553],
       [ 0.94634053, -1.87141502],
       [ 0.33900345,  0.69557019],
       [-0.60010022,  0.69557019],
       [-1.64542971,  0.69557019]])

In [145]:
# for multivariate dataset, you need scaling
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
mysteps = [("mm",MinMaxScaler()),("knn",KNeighborsRegressor())]
mypipeline = Pipeline(steps=mysteps)

from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing()
X = dataset.data
Y = dataset.target

from sklearn.model_selection import KFold,RandomizedSearchCV
kf = KFold(n_splits=5)

combinations = {"knn__n_neighbors" : range(1,11),
                "knn__weights" : ['uniform','distance'],
                "knn__metric"  : ["manhattan","euclidean"]                  
}

rcv = RandomizedSearchCV(mypipeline, param_distributions=combinations, cv=kf, scoring="neg_mean_absolute_error" )
rcv.fit(X,Y)

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=Pipeline(steps=[('mm', MinMaxScaler()),
                                             ('knn', KNeighborsRegressor())]),
                   param_distributions={'knn__metric': ['manhattan',
                                                        'euclidean'],
                                        'knn__n_neighbors': range(1, 11),
                                        'knn__weights': ['uniform',
                                                         'distance']},
                   scoring='neg_mean_absolute_error')

In [146]:
rcv.best_estimator_

Pipeline(steps=[('mm', MinMaxScaler()),
                ('knn',
                 KNeighborsRegressor(metric='euclidean', n_neighbors=8,
                                     weights='distance'))])

In [147]:
rcv.best_params_

{'knn__weights': 'distance', 'knn__n_neighbors': 8, 'knn__metric': 'euclidean'}

In [148]:
rcv.best_score_

-0.5781033522193086

In [149]:
# for multivariate dataset, you need scaling
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
mysteps = [("mm",MinMaxScaler()),("knn",KNeighborsRegressor())]
mypipeline = Pipeline(steps=mysteps)

from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing()
X = dataset.data
Y = dataset.target

from sklearn.model_selection import KFold,GridSearchCV
kf = KFold(n_splits=5)

combinations = {"knn__n_neighbors" : range(1,11),
                "knn__weights" : ['uniform','distance'],
                "knn__metric"  : ["manhattan","euclidean"]                  
}

gcv = GridSearchCV(mypipeline, param_grid=combinations, cv=kf, scoring="neg_mean_absolute_error" )
gcv.fit(X,Y)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('mm', MinMaxScaler()),
                                       ('knn', KNeighborsRegressor())]),
             param_grid={'knn__metric': ['manhattan', 'euclidean'],
                         'knn__n_neighbors': range(1, 11),
                         'knn__weights': ['uniform', 'distance']},
             scoring='neg_mean_absolute_error')

In [150]:
gcv.best_score_

-0.5556467583729019