In [1]:
import pandas as pd 
import numpy as np 
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('Tweets.csv')

# Airline Customers Tweets

df.head(5)

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  570306133677760513           neutral                        1.0000   
1  570301130888122368          positive                        0.3486   
2  570301083672813571           neutral                        0.6837   
3  570301031407624196          negative                        1.0000   
4  570300817074462722          negative                        1.0000   

  negativereason  negativereason_confidence         airline  \
0            NaN                        NaN  Virgin America   
1            NaN                     0.0000  Virgin America   
2            NaN                        NaN  Virgin America   
3     Bad Flight                     0.7033  Virgin America   
4     Can't Tell                     1.0000  Virgin America   

  airline_sentiment_gold        name negativereason_gold  retweet_count  \
0                    NaN     cairdin                 NaN              0   
1                    NaN    jnardino                 NaN              0   
2                    NaN  yvonnalynn                 NaN              0   
3                    NaN    jnardino                 NaN              0   
4                    NaN    jnardino                 NaN              0   

                                                text tweet_coord  \
0                @VirginAmerica What @dhepburn said.         NaN   
1  @VirginAmerica plus you've added commercials t...         NaN   
2  @VirginAmerica I didn't today... Must mean I n...         NaN   
3  @VirginAmerica it's really aggressive to blast...         NaN   
4  @VirginAmerica and it's a really big bad thing...         NaN   

               tweet_created tweet_location               user_timezone  
0  2015-02-24 11:35:52 -0800            NaN  Eastern Time (US & Canada)  
1  2015-02-24 11:15:59 -0800            NaN  Pacific Time (US & Canada)  
2  2015-02-24 11:15:48 -0800      Lets Play  Central Time (US & Canada)  
3  2015-02-24 11:15:36 -0800            NaN  Pacific Time (US & Canada)  
4  2015-02-24 11:14:45 -0800            NaN  Pacific Time (US & Canada)

In [3]:
df['airline_sentiment'].value_counts() # MultiClass Classification Problem

negative    9178
neutral     3099
positive    2363
Name: airline_sentiment, dtype: int64

In [4]:
# f(Airline, Tweet) --> Sentiment .

In [5]:
df['airline'].isna().sum() # No NULL Values as the sum is 0

0

In [6]:
df['airline_sentiment'].isna().sum() # --> Output with no NULL values

0

In [7]:
df['text'].isna().sum()

0

In [8]:
df['airline'] # You need to encode this Nominal feature

0        Virgin America
1        Virgin America
2        Virgin America
3        Virgin America
4        Virgin America
              ...      
14635          American
14636          American
14637          American
14638          American
14639          American
Name: airline, Length: 14640, dtype: object

In [9]:
df['airline'].value_counts()

United            3822
US Airways        2913
American          2759
Southwest         2420
Delta             2222
Virgin America     504
Name: airline, dtype: int64

In [10]:
indexes = np.random.choice(range(df.shape[0]), 2500) # Randomly selecting 2500 indexes
indexes

array([8751, 8480, 4347, ..., 5381, 3099, 5840])

In [11]:
df.loc[indexes, 'airline']

8751         Delta
8480         Delta
4347     Southwest
13424     American
7512         Delta
           ...    
1470        United
1653        United
5381     Southwest
3099        United
5840     Southwest
Name: airline, Length: 2500, dtype: object

In [12]:
pd.get_dummies(df.loc[indexes, 'airline'])

American  Delta  Southwest  US Airways  United  Virgin America
8751          0      1          0           0       0               0
8480          0      1          0           0       0               0
4347          0      0          1           0       0               0
13424         1      0          0           0       0               0
7512          0      1          0           0       0               0
...         ...    ...        ...         ...     ...             ...
1470          0      0          0           0       1               0
1653          0      0          0           0       1               0
5381          0      0          1           0       0               0
3099          0      0          0           0       1               0
5840          0      0          1           0       0               0

[2500 rows x 6 columns]

In [13]:
airline_df = pd.get_dummies(df.loc[indexes, 'airline'])
airline_df.head()

American  Delta  Southwest  US Airways  United  Virgin America
8751          0      1          0           0       0               0
8480          0      1          0           0       0               0
4347          0      0          1           0       0               0
13424         1      0          0           0       0               0
7512          0      1          0           0       0               0

In [14]:
df['text']

0                      @VirginAmerica What @dhepburn said.
1        @VirginAmerica plus you've added commercials t...
2        @VirginAmerica I didn't today... Must mean I n...
3        @VirginAmerica it's really aggressive to blast...
4        @VirginAmerica and it's a really big bad thing...
                               ...                        
14635    @AmericanAir thank you we got on a different f...
14636    @AmericanAir leaving over 20 minutes Late Flig...
14637    @AmericanAir Please bring American Airlines to...
14638    @AmericanAir you have my money, you change my ...
14639    @AmericanAir we have 8 ppl so we need 2 know h...
Name: text, Length: 14640, dtype: object

In [15]:
df.loc[indexes, 'text'].str.lower()

8751     @jetblue i have the emails that they are on th...
8480                @jetblue the best airline in the world
4347     @southwestair  thanks southwest for saving our...
13424    @americanair  i have still not talked to anyon...
7512     @jetblue i know, but i wanted to pass it along...
                               ...                        
1470     @united it was delivered! thank you for making...
1653     @united when i click that link it wants my fli...
5381     @southwestair - i get that weather delays are ...
3099     @united another unfortunate case of bad luck, ...
5840     @southwestair you're going to compensate us fo...
Name: text, Length: 2500, dtype: object

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
# The Input to this CountVectorizer is a collection of strings, an array of strings, a list of strings, a Series of strings.... 
cv.fit(df.loc[indexes, 'text'].str.lower()) # It will compute all the unique words

CountVectorizer()

In [17]:
len(cv.vocabulary_)

5045

In [18]:
cv.vocabulary_

{'jetblue': 2547,
 'have': 2231,
 'the': 4420,
 'emails': 1678,
 'that': 4417,
 'they': 4438,
 'are': 648,
 'on': 3231,
 'their': 4425,
 'way': 4849,
 'best': 847,
 'airline': 505,
 'in': 2394,
 'world': 4957,
 'southwestair': 4160,
 'thanks': 4413,
 'southwest': 4159,
 'for': 1988,
 'saving': 3922,
 'our': 3281,
 'trip': 4558,
 'my': 3053,
 'sweetheart': 4341,
 'isn': 2494,
 'going': 2138,
 'to': 4495,
 'miss': 2987,
 'seeing': 3970,
 'altonbrownlive': 548,
 'all': 529,
 'sohappy': 4123,
 'americanair': 565,
 'still': 4249,
 'not': 3150,
 'talked': 4373,
 'anyone': 616,
 'you': 5022,
 'guys': 2190,
 'should': 4034,
 'be': 812,
 'prepared': 3521,
 'these': 4437,
 'situations': 4079,
 'how': 2331,
 'is': 2490,
 'this': 4446,
 'good': 2144,
 'service': 4000,
 'am': 554,
 'so': 4119,
 'mad': 2835,
 'know': 2634,
 'but': 982,
 'wanted': 4828,
 'pass': 3344,
 'it': 2503,
 'along': 539,
 't5': 4359,
 'experience': 1786,
 'esp': 1733,
 'someone': 4133,
 'who': 4903,
 'flies': 1932,
 'times': 

In [19]:
sorted(cv.vocabulary_)

['00',
 '000',
 '00p',
 '00pm',
 '01',
 '02',
 '03',
 '05am',
 '05pm',
 '0600',
 '07p',
 '08',
 '0ewj7oklji',
 '0jutcdrljl',
 '10',
 '100',
 '1000',
 '1000cost',
 '1020',
 '1028',
 '103',
 '1032',
 '1041',
 '1065',
 '1071',
 '1079871763',
 '10am',
 '10mins',
 '11',
 '110',
 '1101',
 '1114',
 '1117',
 '112',
 '1140',
 '117',
 '1170',
 '118',
 '1183',
 '11am',
 '12',
 '1242',
 '1254',
 '125k',
 '1278',
 '12am',
 '12h',
 '13',
 '130',
 '1300',
 '138',
 '13th',
 '14',
 '140',
 '1415',
 '1472',
 '14am',
 '14th',
 '15',
 '150',
 '150000',
 '1534',
 '1535',
 '1553',
 '1558',
 '1562',
 '1579',
 '1591',
 '15min',
 '15minutes',
 '15p',
 '16',
 '1601',
 '1605',
 '1618',
 '162',
 '1620',
 '1627',
 '1641',
 '165',
 '1665',
 '1687',
 '16hr',
 '16mont',
 '17',
 '1701',
 '1702',
 '1706',
 '1761',
 '1777',
 '1797',
 '17mph',
 '18',
 '180',
 '1814',
 '1855',
 '1856',
 '1874get',
 '1875',
 '1881',
 '1891',
 '18feb',
 '18fmr06mn6',
 '18th',
 '19',
 '1917',
 '1945',
 '1966',
 '19pm',
 '1am',
 '1ateafnc6r',

In [20]:
cv.transform(df.loc[indexes, 'text'].str.lower())

<2500x5045 sparse matrix of type '<class 'numpy.int64'>'
	with 40030 stored elements in Compressed Sparse Row format>

In [21]:
cv.transform(df.loc[indexes, 'text'].str.lower()).todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
data = pd.DataFrame(cv.transform(df.loc[indexes, 'text'].str.lower()).todense(), columns = sorted(cv.vocabulary_))
data.head()

00  000  00p  00pm  01  02  03  05am  05pm  0600  ...  yyz  zero  zfv  \
0   0    0    0     0   0   0   0     0     0     0  ...    0     0    0   
1   0    0    0     0   0   0   0     0     0     0  ...    0     0    0   
2   0    0    0     0   0   0   0     0     0     0  ...    0     0    0   
3   0    0    0     0   0   0   0     0     0     0  ...    0     0    0   
4   0    0    0     0   0   0   0     0     0     0  ...    0     0    0   

   zgoqoxjbqy  zip  zone  zoom  zrh_airport  zurich  zv2pt6trk9  
0           0    0     0     0            0       0           0  
1           0    0     0     0            0       0           0  
2           0    0     0     0            0       0           0  
3           0    0     0     0            0       0           0  
4           0    0     0     0            0       0           0  

[5 rows x 5045 columns]

In [23]:
(data.sum()>10).sum()

532

In [24]:
data.sum().sort_values(ascending = False)[:20]

to              1473
the              970
you              794
united           704
for              686
flight           669
on               656
and              639
my               539
usairways        537
is               501
in               484
americanair      479
southwestair     436
it               430
jetblue          388
of               355
can              326
me               310
your             297
dtype: int64

In [25]:
data_df = data.loc[:,data.sum() > 105]
data_df.shape

(2500, 68)

In [26]:
airline_df.shape

(2500, 6)

In [27]:
airline_df = airline_df.reset_index(drop = True)

In [28]:
X = pd.concat((airline_df, data_df), axis = 1)
Y = df.loc[indexes, 'airline_sentiment'].values

In [29]:
X

American  Delta  Southwest  US Airways  United  Virgin America  all  \
0            0      1          0           0       0               0    0   
1            0      1          0           0       0               0    0   
2            0      0          1           0       0               0    1   
3            1      0          0           0       0               0    0   
4            0      1          0           0       0               0    0   
...        ...    ...        ...         ...     ...             ...  ...   
2495         0      0          0           0       1               0    0   
2496         0      0          0           0       1               0    0   
2497         0      0          1           0       0               0    0   
2498         0      0          0           0       1               0    0   
2499         0      0          1           0       0               0    0   

      americanair  amp  an  ...  usairways  virginamerica  was  we  what  why  \
0               0    0   0  ...          0              0    0   0     0    0   
1               0    0   0  ...          0              0    0   0     0    0   
2               0    0   0  ...          0              0    0   0     0    0   
3               1    0   0  ...          0              0    0   0     0    0   
4               0    0   0  ...          0              0    0   0     0    0   
...           ...  ...  ..  ...        ...            ...  ...  ..   ...  ...   
2495            0    0   0  ...          0              0    1   0     0    0   
2496            0    0   0  ...          0              0    0   0     0    0   
2497            0    0   0  ...          0              0    0   0     0    0   
2498            0    0   0  ...          0              0    0   0     0    0   
2499            0    0   0  ...          0              0    0   0     0    0   

      will  with  you  your  
0        0     0    0     0  
1        0     0    0     0  
2        0     0    0     0  
3        0     0    1     0  
4        0     0    0     0  
...    ...   ...  ...   ...  
2495     0     0    1     0  
2496     0     0    1     0  
2497     0     0    1     1  
2498     1     0    0     0  
2499     0     0    1     0  

[2500 rows x 74 columns]

In [30]:
Y

array(['neutral', 'positive', 'positive', ..., 'negative', 'negative',
       'neutral'], dtype=object)

In [31]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
skf = StratifiedKFold(n_splits=5)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=1)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.656 0.654 0.65  0.666 0.644] 
------------------------------- 
Avg 5 Folds 0.654


In [32]:
from sklearn.ensemble import AdaBoostClassifier
dt = DecisionTreeClassifier(random_state=1)
model = AdaBoostClassifier(estimator=dt,random_state=1)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.61  0.7   0.64  0.646 0.636] 
------------------------------- 
Avg 5 Folds 0.6464000000000001


In [33]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=1)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.722 0.758 0.726 0.764 0.754] 
------------------------------- 
Avg 5 Folds 0.7447999999999999


In [34]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(random_state=1)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.714 0.734 0.738 0.724 0.712] 
------------------------------- 
Avg 5 Folds 0.7243999999999999


In [35]:
from sklearn.ensemble import HistGradientBoostingClassifier
model = HistGradientBoostingClassifier(random_state=1)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.706 0.748 0.736 0.738 0.746] 
------------------------------- 
Avg 5 Folds 0.7348


In [36]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=1,max_iter=1000)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.702 0.742 0.738 0.712 0.712] 
------------------------------- 
Avg 5 Folds 0.7212


In [37]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.714 0.734 0.73  0.722 0.712] 
------------------------------- 
Avg 5 Folds 0.7224


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
sv = SVC(kernel='rbf',probability=True)
model = AdaBoostClassifier(estimator=sv)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

In [39]:
from sklearn.ensemble import AdaBoostClassifier
lr = LogisticRegression(max_iter=1000)
model = AdaBoostClassifier(estimator=lr)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.706 0.726 0.736 0.708 0.71 ] 
------------------------------- 
Avg 5 Folds 0.7172000000000001


In [40]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(Y)

In [41]:
# xgboost - if we tune will cross every other library
import xgboost as xgb 
model = xgb.XGBClassifier()

results = cross_val_score(model,X,y_encoded, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.712 0.744 0.71  0.718 0.752] 
------------------------------- 
Avg 5 Folds 0.7272000000000001


In [42]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(verbose=False)

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[0.73  0.736 0.724 0.748 0.732] 
------------------------------- 
Avg 5 Folds 0.734


In [43]:
# lightgbm - good for large datasets
from lightgbm import LGBMClassifier

model = LGBMClassifier()

results = cross_val_score(model,X,Y, cv=skf,scoring='accuracy')
print(results,"\n-------------------------------","\nAvg 5 Folds",results.mean())

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001303 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 237
[LightGBM] [Info] Number of data points in the train set: 2000, number of used features: 72
[LightGBM] [Info] Start training from score -0.453343
[LightGBM] [Info] Start training from score -1.632195
[LightGBM] [Info] Start training from score -1.777857
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000873 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 237
[LightGBM] [Info] Number of data points in the train set: 2000, numb

In [44]:
import warnings
warnings.filterwarnings('ignore')

In [45]:
# lazy predict

from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=.5,random_state =123)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
models

 90%|████████▉ | 26/29 [00:08<00:00,  3.81it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002110 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 294
[LightGBM] [Info] Number of data points in the train set: 1250, number of used features: 72
[LightGBM] [Info] Start training from score -0.461401
[LightGBM] [Info] Start training from score -1.633731
[LightGBM] [Info] Start training from score -1.746404


100%|██████████| 29/29 [00:08<00:00,  3.45it/s]


Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
NearestCentroid                    0.65               0.61    None      0.67   
LGBMClassifier                     0.72               0.60    None      0.71   
SGDClassifier                      0.69               0.60    None      0.69   
ExtraTreesClassifier               0.72               0.58    None      0.70   
LinearDiscriminantAnalysis         0.72               0.58    None      0.70   
RandomForestClassifier             0.73               0.58    None      0.71   
LogisticRegression                 0.70               0.57    None      0.69   
BernoulliNB                        0.69               0.57    None      0.68   
LinearSVC                          0.71               0.56    None      0.69   
SVC                                0.72               0.56    None      0.70   
RidgeClassifierCV                  0.73               0.56    None      0.70   
AdaBoostClassifier                 0.69               0.56    None      0.68   
BaggingClassifier                  0.69               0.56    None      0.67   
KNeighborsClassifier               0.62               0.56    None      0.64   
RidgeClassifier                    0.72               0.56    None      0.70   
PassiveAggressiveClassifier        0.68               0.55    None      0.66   
CalibratedClassifierCV             0.73               0.55    None      0.69   
GaussianNB                         0.52               0.54    None      0.55   
DecisionTreeClassifier             0.62               0.54    None      0.63   
LabelPropagation                   0.66               0.53    None      0.65   
LabelSpreading                     0.66               0.53    None      0.65   
Perceptron                         0.67               0.52    None      0.65   
ExtraTreeClassifier                0.60               0.50    None      0.61   
QuadraticDiscriminantAnalysis      0.41               0.45    None      0.42   
DummyClassifier                    0.64               0.33    None      0.50   

                               Time Taken  
Model                                      
NearestCentroid                      0.07  
LGBMClassifier                       0.36  
SGDClassifier                        0.14  
ExtraTreesClassifier                 0.40  
LinearDiscriminantAnalysis           0.09  
RandomForestClassifier               0.82  
LogisticRegression                   0.18  
BernoulliNB                          0.04  
LinearSVC                            0.94  
SVC                                  0.43  
RidgeClassifierCV                    0.10  
AdaBoostClassifier                   0.37  
BaggingClassifier                    0.15  
KNeighborsClassifier                 0.20  
RidgeClassifier                      0.07  
PassiveAggressiveClassifier          0.09  
CalibratedClassifierCV               2.91  
GaussianNB                           0.04  
DecisionTreeClassifier               0.04  
LabelPropagation                     0.24  
LabelSpreading                       0.32  
Perceptron                           0.07  
ExtraTreeClassifier                  0.05  
QuadraticDiscriminantAnalysis        0.14  
DummyClassifier                      0.02

In [ ]:
# H20.ai(paid)

#

In [32]:
X

American  Delta  Southwest  US Airways  United  Virgin America  all  \
0            1      0          0           0       0               0    0   
1            0      0          0           0       1               0    0   
2            0      0          0           1       0               0    0   
3            0      0          1           0       0               0    0   
4            0      0          0           0       1               0    0   
...        ...    ...        ...         ...     ...             ...  ...   
2495         0      0          0           0       1               0    0   
2496         0      0          1           0       0               0    0   
2497         0      0          0           1       0               0    0   
2498         0      0          0           1       0               0    0   
2499         1      0          0           0       0               0    0   

      americanair  amp  an  ...  us  usairways  was  we  what  why  will  \
0               1    0   0  ...   0          0    0   0     0    0     0   
1               0    0   0  ...   0          0    0   0     0    0     0   
2               1    0   0  ...   0          1    0   0     0    0     0   
3               0    0   0  ...   0          0    0   0     0    0     0   
4               0    0   0  ...   0          0    0   0     0    0     0   
...           ...  ...  ..  ...  ..        ...  ...  ..   ...  ...   ...   
2495            0    1   0  ...   0          0    0   1     0    0     0   
2496            0    0   0  ...   0          0    0   0     1    0     0   
2497            0    0   0  ...   0          1    0   0     0    0     0   
2498            0    0   0  ...   0          1    1   0     0    0     0   
2499            1    0   0  ...   1          0    0   0     0    0     0   

      with  you  your  
0        0    0     0  
1        0    0     0  
2        0    0     0  
3        0    1     0  
4        1    2     1  
...    ...  ...   ...  
2495     0    0     0  
2496     0    0     0  
2497     0    1     0  
2498     0    0     0  
2499     0    1     0  

[2500 rows x 67 columns]

In [31]:
from pycaret.classification import *

X['output'] = Y 
X.head(5)

# pycaret needs a dataframe , with the target column(s)
s = setup(X,target='output')

In [32]:
compare_models()

Processing:   0%|          | 0/69 [00:00<?, ?it/s]

In [33]:
models()

Name  \
ID                                          
lr                    Logistic Regression   
knn                K Neighbors Classifier   
nb                            Naive Bayes   
dt               Decision Tree Classifier   
svm                   SVM - Linear Kernel   
rbfsvm                SVM - Radial Kernel   
gpc           Gaussian Process Classifier   
mlp                        MLP Classifier   
ridge                    Ridge Classifier   
rf               Random Forest Classifier   
qda       Quadratic Discriminant Analysis   
ada                  Ada Boost Classifier   
gbc          Gradient Boosting Classifier   
lda          Linear Discriminant Analysis   
et                 Extra Trees Classifier   
xgboost         Extreme Gradient Boosting   
lightgbm  Light Gradient Boosting Machine   
catboost              CatBoost Classifier   
dummy                    Dummy Classifier   

                                                  Reference  Turbo  
ID                                                                  
lr        sklearn.linear_model._logistic.LogisticRegression   True  
knn       sklearn.neighbors._classification.KNeighborsCl...   True  
nb                           sklearn.naive_bayes.GaussianNB   True  
dt             sklearn.tree._classes.DecisionTreeClassifier   True  
svm       sklearn.linear_model._stochastic_gradient.SGDC...   True  
rbfsvm                             sklearn.svm._classes.SVC  False  
gpc       sklearn.gaussian_process._gpc.GaussianProcessC...  False  
mlp       sklearn.neural_network._multilayer_perceptron....  False  
ridge           sklearn.linear_model._ridge.RidgeClassifier   True  
rf          sklearn.ensemble._forest.RandomForestClassifier   True  
qda       sklearn.discriminant_analysis.QuadraticDiscrim...   True  
ada       sklearn.ensemble._weight_boosting.AdaBoostClas...   True  
gbc         sklearn.ensemble._gb.GradientBoostingClassifier   True  
lda       sklearn.discriminant_analysis.LinearDiscrimina...   True  
et            sklearn.ensemble._forest.ExtraTreesClassifier   True  
xgboost                       xgboost.sklearn.XGBClassifier   True  
lightgbm                    lightgbm.sklearn.LGBMClassifier   True  
catboost                   catboost.core.CatBoostClassifier   True  
dummy                         sklearn.dummy.DummyClassifier   True

In [34]:
hyper_params = {'n_estimators':range(75, 125, 7),
                'max_samples':np.linspace(0.5, 1, 6),
                #'ccp_alpha':np.linspace(0, 0.0005, 5),
                'max_features':np.linspace(0.05, 0.3,6),
                'criterion':['gini','entropy']
               }

In [35]:
myrf = create_model('rf')
tuned_model = tune_model(myrf, custom_grid = hyper_params)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


In [36]:
tuned_model

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features=0.05,
                       max_leaf_nodes=None, max_samples=0.9,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=82, n_jobs=-1, oob_score=False,
                       random_state=777, verbose=0, warm_start=False)

In [37]:
tuned_model.predict(X[:100].drop('output',axis=1))

array([1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 2, 2, 1, 0, 1, 2, 0, 2, 2, 0, 0, 0,
       2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0])

In [38]:
tuned_model.predict_proba(X[:100].drop('output',axis=1))

array([[0.20731707, 0.65853659, 0.13414634],
       [0.12195122, 0.27746322, 0.60058556],
       [0.09756098, 0.07317073, 0.82926829],
       [0.85365854, 0.03658537, 0.1097561 ],
       [0.87804878, 0.07317073, 0.04878049],
       [0.85365854, 0.07317073, 0.07317073],
       [0.8902439 , 0.06097561, 0.04878049],
       [0.98170732, 0.01829268, 0.        ],
       [0.87804878, 0.02439024, 0.09756098],
       [0.90243902, 0.06097561, 0.03658537],
       [0.07317073, 0.91463415, 0.01219512],
       [0.20731707, 0.69512195, 0.09756098],
       [0.91463415, 0.04878049, 0.03658537],
       [0.88414634, 0.04268293, 0.07317073],
       [0.87804878, 0.03658537, 0.08536585],
       [0.27256098, 0.39817073, 0.32926829],
       [0.14634146, 0.79268293, 0.06097561],
       [0.82926829, 0.12195122, 0.04878049],
       [0.20731707, 0.09756098, 0.69512195],
       [0.93902439, 0.02439024, 0.03658537],
       [0.57317073, 0.37804878, 0.04878049],
       [0.90243902, 0.06097561, 0.03658537],
       [0.

In [39]:
X.columns

Index(['American', 'Delta', 'Southwest', 'US Airways', 'United',
       'Virgin America', 'all', 'americanair', 'amp', 'an', 'and', 'are', 'at',
       'be', 'been', 'but', 'can', 'cancelled', 'co', 'customer', 'delayed',
       'do', 'flight', 'flights', 'for', 'from', 'get', 'have', 'help', 'hold',
       'hours', 'how', 'http', 'if', 'in', 'is', 'it', 'jetblue', 'just', 'me',
       'my', 'no', 'not', 'now', 'of', 'on', 'our', 'out', 'service', 'so',
       'southwestair', 'still', 'thank', 'thanks', 'that', 'the', 'there',
       'they', 'this', 'time', 'to', 'united', 'up', 'us', 'usairways',
       'virginamerica', 'was', 'we', 'what', 'why', 'will', 'with', 'you',
       'your', 'output'],
      dtype='object')

In [40]:
tune_model(myrf,search_library='optuna')

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

[I 2024-01-05 19:56:31,445] Searching the best hyperparameters using 1750 samples...
[I 2024-01-05 19:57:14,990] Finished hyperparameter search!


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=777, verbose=0, warm_start=False)

In [41]:
tune_model(myrf,search_library='scikit-optimize')

ModuleNotFoundError: 
'skopt' is a soft dependency and not included in the pycaret installation. Please run: `pip install scikit-optimize` to install.
Alternately, you can install this by running `pip install pycaret[tuners]`

In [41]:
tuned_model.feature_importances_

array([0.00899141, 0.01167563, 0.01146716, 0.01199454, 0.01015189,
       0.01139968, 0.00699235, 0.01021861, 0.00995055, 0.01139708,
       0.02804846, 0.01079435, 0.01775243, 0.01351114, 0.0063249 ,
       0.0117027 , 0.0169328 , 0.01011632, 0.020521  , 0.00879552,
       0.01224404, 0.02534318, 0.00860571, 0.02912868, 0.012921  ,
       0.01264667, 0.01301727, 0.01015482, 0.00626466, 0.01535021,
       0.02312508, 0.0230009 , 0.0221243 , 0.01419124, 0.01187053,
       0.01797068, 0.02322524, 0.01677234, 0.01875758, 0.01056436,
       0.018808  , 0.02485622, 0.00723575, 0.00682452, 0.00700659,
       0.01105585, 0.01155798, 0.01101428, 0.02792741, 0.01770357,
       0.04058669, 0.00923058, 0.01184148, 0.00888503, 0.04248482,
       0.01296083, 0.00938104, 0.00718902, 0.01079016, 0.01346259,
       0.01278845, 0.01042443, 0.00776008, 0.01159133, 0.01573239,
       0.03777537, 0.01710854])

In [44]:
pd.DataFrame(tuned_model.feature_importances_, index=X.columns[:X.shape[1]-1],columns=['Importance']).sort_values('Importance',ascending = False)

Importance
to       0.042485
the      0.040587
you      0.037775
for      0.029129
and      0.028048
...           ...
plane    0.007007
all      0.006992
out      0.006825
been     0.006325
hours    0.006265

[67 rows x 1 columns]

In [ ]:
# Any decision tree based ensemble model give feature importance
# Random Forest, Adaboost, Gradient Boosting

In [48]:
# Combine Heterogeneous Models - Hard voting

from sklearn.ensemble import  VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import  SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import  train_test_split

inp = X.drop('output',axis=1)
output = X['output']
x_train,x_test,y_train,y_test = train_test_split(inp,output,test_size = 0.3)
mymodels =  [('lr',LogisticRegression()),('sv',SVC(probability = True)),('dt',DecisionTreeClassifier())]

vc = VotingClassifier(mymodels, voting = 'hard')
vc.fit(x_train,y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('sv',
                              SVC(C=1.0, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=0.0,
                                  de...
                                  shrinking=True, tol=0.001, verbose=False)),
                             ('dt',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     random_state=None,
                                                     splitter='best'))],
                 flatten_transform=True, n_jobs=None, verbose=False,
                 voting='hard', weights=None)

In [52]:
vc.predict(x_test[:100])

array(['negative', 'negative', 'positive', 'neutral', 'negative',
       'negative', 'negative', 'negative', 'neutral', 'neutral',
       'negative', 'negative', 'negative', 'positive', 'negative',
       'negative', 'neutral', 'negative', 'negative', 'neutral',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'neutral',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'neutral', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'positive',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'neutral', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'neutral', 'negative', 'neutral',
     

In [54]:
from sklearn.metrics import  accuracy_score
accuracy_score(y_test,vc.predict(x_test))

0.6973333333333334

In [66]:
# Combine Heterogeneous Models - soft voting
inp = X.drop('output',axis=1)
output = X['output'].map({"positive" : 1, "negative" : 2, "neutral" : 0})
x_train,x_test,y_train,y_test = train_test_split(inp,output,test_size = 0.3)
mymodels =  [('lr',LogisticRegression()),('sv',SVC(probability = True)),('dt',DecisionTreeClassifier())]

vc = VotingClassifier(mymodels, voting = 'soft',weights=[0.3,0.5,0.2])
vc.fit(x_train,y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('sv',
                              SVC(C=1.0, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=0.0,
                                  de...
                                  shrinking=True, tol=0.001, verbose=False)),
                             ('dt',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     random_state=None,
                                                     splitter='best'))],
                 flatten_transform=True, n_jobs=None, verbose=False,
                 voting='soft', weights=[0.3, 0.5, 0.2])

In [67]:
accuracy_score(y_test,vc.predict(x_test))

0.708

In [68]:
vc.estimators_[1].predict(x_test)

array([2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 1, 2, 0,
       2, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       1, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,

In [69]:
accuracy_score(y_test,vc.estimators_[1].predict(x_test))

0.6946666666666667

In [70]:
accuracy_score(y_test,vc.estimators_[0].predict(x_test))

0.6826666666666666

In [71]:
accuracy_score(y_test,vc.estimators_[2].predict(x_test))

0.6013333333333334